"""Present actual maze ordering and generation in the same visible scene."""
from pathlib import Path
from bs4 import BeautifulSoup
root=Path(__file__).resolve().parents[1];s=BeautifulSoup((root/'index.html').read_text(),'html.parser')
def viewer(key,title,classes=''):
 return f'<div class="viewer maze-method-viewer {classes}" data-scene="{key}" data-title="{title}"><img class="preview-image" src="assets/media/{key}.png" alt="{title}" width="900" height="650" loading="lazy"><button type="button" class="launch">Explore in 3D</button></div>'
order=s.find(id='method-order');flow=s.find(id='method-flow')
for article in [order,flow]:
 for node in list(article.children):
  if getattr(node,'name',None) and node.name not in ['h3','details']:node.decompose()
order.find('h3').insert_after(BeautifulSoup('''<p class="method-lead">Learn which objects participate and which should come first.</p><p class="method-small-copy">Reference plans teach the model which objects to move and their relative order. For a new scene, the trained model predicts selection probabilities and priority distributions. Sampling these distributions gives an interaction order.</p><div class="maze-order-layout">'''+viewer('method-order-maze','Maze context for object selection and ordering')+'''<div class="maze-order-readout"><p class="context-source">G1 · object states · scene geometry</p><p class="context-target">Planning context H</p><table class="maze-selection-table"><caption>Predictions conditioned on this context</caption><thead><tr><th>Object</th><th>Selection</th><th>Priority</th></tr></thead><tbody id="maze-selection-rows"></tbody></table><p class="maze-order-result" id="maze-order-result" aria-live="polite"></p><div class="control-row"><button id="maze-order-next" type="button">Next saved sample</button><output id="maze-order-sample"></output></div><p class="figure-caption">Curves show the learned priority distributions. Markers show the sampled priorities. Lower priorities come first among selected objects. These four saved draws retain the same order.</p></div></div>''','html.parser'))
flow.find('h3').insert_after(BeautifulSoup('''<p class="method-lead">Generate object motion in the selected order.</p><p class="method-small-copy">Each object can use the observed context and generated targets at earlier ranks. Later ranks remain masked.</p><div class="control-row maze-flow-controls"><label>Noise draw <select id="maze-flow-sample"><option value="0">1</option><option value="1">2</option><option value="2">3</option><option value="3">4</option></select></label></div>'''+viewer('method-flow-0-refined','Rank causal object generation in a maze','maze-flow-viewer')+'''<div class="generation-progress"><button type="button" id="flow-play">Pause generation</button><button type="button" id="flow-replay">Replay</button><span>t = 0</span><progress id="flow-progress" value="0" max="1" aria-label="Generation time"></progress><output id="flow-time">0.00</output><span>t = 1</span></div><p class="figure-caption" id="maze-flow-caption" aria-live="polite">This animation combines learned motion generation with geometric smoothing and clearance checks. The displayed paths account for walls, other objects, and the observed robot footprint. These geometric checks do not certify physical execution.</p><p class="figure-caption">Four outlined anchors mark each generated path above the object tops for visibility. Two dashed boxes show the target poses. Generation runs from t = 0 to t = 1 and can be paused or replayed. This is generation time, not robot execution time. Frames between the 30 recorded Euler steps are interpolated for display. The robot and solid objects remain at their observed poses.</p>''','html.parser'))
s.select_one('.maze-flow-viewer')['data-generation']='true'
s.select_one('#method-order .viewer')['data-order-stage']='sampling'
old=s.find('script',src='assets/method-trace.js')
if old:old.decompose()
for source in ['assets/maze-method-trace.js','assets/maze-method.js']:
 if not s.find('script',src=source):s.head.append(s.new_tag('script',attrs={'src':source,'defer':''}))
(root/'index.html').write_text(str(s).rstrip()+'\n')
