"""Install dataset explorers and the recorded MPC process comparison."""
from pathlib import Path
from bs4 import BeautifulSoup
root=Path(__file__).resolve().parents[1];s=BeautifulSoup((root/'index.html').read_text(),'html.parser')
for kind,title,copy in [
 ('grounding','From an observed attempt to a training sample','A mobility sample combines robot structure, scene geometry, and a directed query. A recorded attempt supplies a binary target for a safe crossing. These labels train the shared encoder and the affordance head.'),
 ('ordering','From a reference rollout to selection and order','A plan sample pairs the observed scene and robot structure with a successful reference rollout. Object participation supplies selection targets. The reference sequence supplies relative ranks, and the object paths supply motion targets.')]:
 old=s.find(id='learning-'+kind)
 if old:old.decompose()
 html=f'''<section id="learning-{kind}" class="learning-explorer" data-kind="{kind}" aria-label="{title}"><h4>{title}</h4><p class="method-small-copy">{copy}</p><div class="learning-loading" role="status">The sample explorer loads when this section is nearby.</div><div class="learning-content" hidden><div class="sample-explorer-grid"><figure><svg class="sample-scatter" viewBox="0 0 480 350" aria-label="Interactive t-SNE sample projection"></svg><figcaption>Hover, focus, or select a point to inspect its recorded sample.</figcaption><div class="sample-legend"><span><i class="body-g1"></i>G1</span><span><i class="body-arm"></i>Spot + arm</span><span>Filled: training</span><span>Outlined: validation</span></div><p class="sample-count"></p></figure><div class="sample-inspector"><h5 class="sample-title"></h5><canvas class="sample-scene" width="560" height="390" aria-label="Recorded robot and object rollout viewed from above"></canvas><div class="sample-controls"><button type="button" class="sample-play">Pause rollout</button><input class="sample-progress" aria-label="Recorded rollout position" type="range" min="0" max="1" step="0.001" value="0"><output class="sample-time"></output></div><p class="sample-inputs"></p><div class="sample-target"></div><div class="sample-pagination"><button type="button" class="sample-prev">Previous sample</button><button type="button" class="sample-next">Next sample</button></div></div></div><p class="sample-projection-note figure-caption"></p><div class="learning-dataflow" aria-label="Supervised learning flow"><span>Observed sample</span><span>Shared encoder</span><span>Prediction and target</span><span>Loss and update</span></div><p class="learning-loss method-small-copy"></p></div></section>'''
 fragment=BeautifulSoup(html,'html.parser')
 article=s.find(id='method-'+('order' if kind=='ordering' else kind))
 if kind=='grounding':article.find(id='embodiment-demo').insert_after(fragment)
 else:article.select_one('.maze-order-layout').insert_before(fragment)
old=s.find(id='mpc-process')
if old:old.decompose()
html='''<section id="mpc-process" class="mpc-process"><h4>Sampling, optimization, and the next control segment</h4><p class="method-small-copy">Execution continues across control updates. Recorded motion remains on the left of the moving time origin, while each saved candidate population extends into the future. Paired dashed leaders connect the active observation to its magnified contact view.</p><div class="mpc-process-loading" role="status">The optimization replay loads when this section is nearby.</div><div class="mpc-process-content" hidden><div class="mpc-process-controls"><button type="button" id="mpc-process-play">Pause</button><button type="button" id="mpc-process-replay">Replay sequence</button><label>Replay time <input id="mpc-process-update" type="range" min="0" max="1" step="0.001" value="0"></label><output id="mpc-process-counter"></output></div><div class="mpc-stages" aria-label="MPC update stage"><span>Sample futures</span><span>Score and select</span><span>Apply command</span><span>Observe again</span></div><div class="mpc-process-pair">'''
for key,title in [('optimized','MPC w/ optimization (ours)'),('baseline','MPC (SUMO)')]:
 html+=f'''<figure data-process="{key}"><h5>{title}</h5><canvas width="560" height="400" aria-label="{title} recorded palm displacement over prediction time"></canvas><div class="mpc-process-readout"></div><figcaption>Dark traces show observed motion. Thin gray paths show candidates, colored paths show selected candidates, and the bold colored path shows the applied prediction. The white marker follows the observed palm. Each inset uses the same time and distance scale.</figcaption></figure>'''
html+='''</div><p class="figure-caption">Both panels use the same distance scale and elapsed replay time. The default view compares the first 0.6 s of each prediction. Show full horizons reveals SUMO’s complete 2.5 s prediction without changing either trace. Past motion comes from recorded physical states, with interpolation between observations. The explorer displays 240 saved SUMO populations from 801 updates and all 140 optimized populations. A saved population remains visible until the next available record.</p><p class="figure-caption">Candidate spread describes the controller’s search space, rather than control quality. Our controller searches bounded contact residuals, while native SUMO searches base commands over a longer horizon. Object progress and goal error show what was physically achieved. Each replay stops at its recorded endpoint. No unrecorded optimization iterations are synthesized.</p></div></section>'''
s.find(id='method-execution').find('details').insert_before(BeautifulSoup(html,'html.parser'))
objects=s.select_one('.viewer[data-scene="objects"]').find_next_sibling('p')
objects.string='Five equally sized anchors and outlined lanes describe each motion. Two corner ghosts mark the next targets on both the outward and return paths. Colored arrows indicate illustrative force directions, not measured forces.'
execution=s.find(id='method-execution')
for label in execution.select('.ego-inset figcaption'):label.string='Body contact detail' if label.find_parent(class_='viewer')['data-scene']=='mpc-baseline' else 'Ego RGB + paired palm regions'
for paragraph in execution.find_all('p'):
 if paragraph.get_text().startswith('The contact field is recomputed'):
  paragraph.string='The faint surface field shows learned contact scores. Two outlined regions locate the recorded left and right palms projected onto the object. These geometric contact neighborhoods are separate from the learned affordance field and do not assert measured contact forces.'
for source in ['assets/learning-explorer.js','assets/mpc-process.js']:
 if not any(t.get('src','').split('?')[0]==source for t in s.find_all('script')):s.head.append(s.new_tag('script',attrs={'src':source,'defer':''}))
(root/'index.html').write_text(str(s).rstrip()+'\n')
