"""Install dataset explorers and the recorded MPC process comparison."""
from pathlib import Path
from bs4 import BeautifulSoup
root=Path(__file__).resolve().parents[1];s=BeautifulSoup((root/'index.html').read_text(),'html.parser')
for kind,title,copy in [
 ('grounding','From an observed attempt to a training sample','A mobility sample combines robot structure, scene geometry, and a directed query. A recorded attempt supplies a binary target for a safe crossing. These labels train the shared encoder and the affordance head.'),
 ('ordering','From a reference rollout to selection and order','A plan sample pairs the observed scene and robot structure with a successful reference rollout. Object participation supplies selection targets. The reference sequence supplies relative ranks, and the object paths supply motion targets.')]:
 old=s.find(id='learning-'+kind)
 if old:old.decompose()
 html=f'''<section id="learning-{kind}" class="learning-explorer" data-kind="{kind}" aria-label="{title}"><h4>{title}</h4><p class="method-small-copy">{copy}</p><div class="learning-loading" role="status">The sample explorer loads when this section is nearby.</div><div class="learning-content" hidden><div class="sample-explorer-grid"><figure><svg class="sample-scatter" viewBox="0 0 480 350" aria-label="Interactive t-SNE sample projection"></svg><figcaption>Hover, focus, or select a point to inspect its recorded sample.</figcaption><div class="sample-legend"><span><i class="body-g1"></i>G1</span><span><i class="body-arm"></i>Spot + arm</span><span>Filled: training</span><span>Outlined: validation</span></div><p class="sample-count"></p></figure><div class="sample-inspector"><h5 class="sample-title"></h5><canvas class="sample-scene" width="560" height="390" aria-label="Recorded robot and object rollout viewed from above"></canvas><div class="sample-controls"><button type="button" class="sample-play">Pause rollout</button><input class="sample-progress" aria-label="Recorded rollout position" type="range" min="0" max="1" step="0.001" value="0"><output class="sample-time"></output></div><p class="sample-inputs"></p><div class="sample-target"></div><div class="sample-pagination"><button type="button" class="sample-prev">Previous sample</button><button type="button" class="sample-next">Next sample</button></div></div></div><p class="sample-projection-note figure-caption"></p><div class="learning-dataflow" aria-label="Supervised learning flow"><span>Observed sample</span><span>Shared encoder</span><span>Prediction and target</span><span>Loss and update</span></div><p class="learning-loss method-small-copy"></p></div></section>'''
 fragment=BeautifulSoup(html,'html.parser')
 article=s.find(id='method-'+('order' if kind=='ordering' else kind))
 if kind=='grounding':article.find(id='embodiment-demo').insert_after(fragment)
 else:article.select_one('.maze-order-layout').insert_before(fragment)
old=s.find(id='mpc-process')
if old:old.decompose()
html='''<section id="mpc-process" class="mpc-process"><h4>Sampling, optimization, and the next control segment</h4><p class="method-small-copy">At each recorded update, both controllers evaluate 24 candidate futures over 0.6 s. The selected command runs for 0.1 s before the next observation. Ours selects a diverse elite set in palm space. The baseline refits direct joint commands and applies their elite mean.</p><div class="mpc-process-loading" role="status">The optimization replay loads when this section is nearby.</div><div class="mpc-process-content" hidden><div class="mpc-process-controls"><button type="button" id="mpc-process-play">Pause</button><button type="button" id="mpc-process-replay">Replay update</button><label>Recorded update <input id="mpc-process-update" type="range" min="0" max="1" step="0.001" value="0"></label><output id="mpc-process-counter"></output></div><div class="mpc-stages" aria-label="MPC update stage"><span>Sample futures</span><span>Score and select</span><span>Apply command</span><span>Observe again</span></div><div class="mpc-process-pair">'''
for key,title in [('optimized','Palm tracking MPC (ours)'),('baseline','Naive MPC')]:
 html+=f'''<figure data-process="{key}"><h5>{title}</h5><canvas width="560" height="400" aria-label="{title} recorded palm displacement over prediction time"></canvas><div class="mpc-process-readout"></div><figcaption>Dots mark 0.1 s palm waypoints. The shaded interval is the applied segment. Both panels share a displacement scale. White markers track the applied segment and observed object progress.</figcaption></figure>'''
html+='''</div><p class="figure-caption">Curves show recorded palm displacement along the commanded push direction. Thin paths show the recorded candidate population. Colored paths identify the recorded elites, and outlined waypoints mark the applied candidate. The baseline includes a separately simulated preview of the elite mean. Each panel retains its own simulation timestamps.</p><p class="figure-caption">The stages are paced for explanation. Paths, costs, elite membership, and applied commands come from recorded optimization updates. The animation does not report inference latency or unrecorded intermediate optimizer iterations.</p></div></section>'''
s.find(id='method-execution').find('details').insert_before(BeautifulSoup(html,'html.parser'))
objects=s.select_one('.viewer[data-scene="objects"]').find_next_sibling('p')
objects.string='Five equally sized anchors and outlined lanes describe each motion. Two corner ghosts mark the next targets on both the outward and return paths. Colored arrows indicate illustrative force directions, not measured forces.'
execution=s.find(id='method-execution')
for label in execution.select('.ego-inset figcaption'):label.string='Ego RGB + paired palm regions'
for paragraph in execution.find_all('p'):
 if paragraph.get_text().startswith('The contact field is recomputed'):
  paragraph.string='The faint surface field shows learned contact scores. Two outlined regions locate the recorded left and right palms projected onto the object. These geometric contact neighborhoods are separate from the learned affordance field and do not assert measured contact forces.'
for source in ['assets/learning-explorer.js','assets/mpc-process.js']:
 if not any(t.get('src','').split('?')[0]==source for t in s.find_all('script')):s.head.append(s.new_tag('script',attrs={'src':source,'defer':''}))
(root/'index.html').write_text(str(s).rstrip()+'\n')
