"""Present the paired physical execution with synchronized ego contact insets."""
from pathlib import Path
from bs4 import BeautifulSoup
root=Path(__file__).resolve().parents[1];soup=BeautifulSoup((root/'index.html').read_text(),'html.parser');article=soup.find(id='method-execution')
parts=['<h3>(d) Execution and replanning</h3><p class="method-lead">The controller tracks object targets and updates its commands from new observations.</p><div class="experiment-matrix paired-matrix mpc-comparison">']
for scene,title,detail in [('mpc-optimized','MPC w/ optimization (ours)','Cartesian palm targets guide the arms through the push.'),('mpc-baseline','MPC (SUMO)','Native SUMO permits whole-body contact. The box moves 0.70 m before progress stalls.')]:
 ego_label='Body contact detail' if scene=='mpc-baseline' else 'Ego RGB + paired palm regions'
 parts.append(f'''<article><h4>{title}</h4><div class="viewer experiment-viewer" data-scene="{scene}" data-title="{title}" data-ego="true"><img class="preview-image" src="assets/media/{scene}.png" alt="Robot, object targets, and recorded candidate palm paths" width="700" height="540" loading="lazy"><button class="launch" type="button">Play in 3D</button><figure class="ego-inset"><video muted playsinline preload="none" poster="assets/media/{scene}-ego.png"><source src="assets/media/{scene}-ego.mp4" type="video/mp4"></video><figcaption>{ego_label}</figcaption></figure></div><p class="method-small-copy">{detail}</p></article>''')
parts.append('''</div><p class="figure-caption">Five elevated anchors summarize each object reference path. Green marks ours and red marks the baseline. Thin curves show sampled palm trajectories, while the thick curve shows the executed candidate. Each inset follows the same playback time as its 3D scene.</p><p class="method-small-copy">The optimized replay shows a faint learned contact field with two outlined palm neighborhoods. The SUMO replay marks whole-body contact locations. Its side view hides walls to expose these contacts. Both follow recorded physical states.</p><details class="method-details"><summary>Replay and controller details</summary><p>Both panels use the same box geometry and target reference from a development scene. The optimized controller uses a 0.6 s horizon and a 0.1 s control interval. Native SUMO uses a 2.5 s horizon and a 0.05 s control interval. Both evaluate 24 candidates. Recorded durations are preserved. SUMO body motion is displayed at 50 Hz and candidate overlays at 10 Hz.</p><p>The optimized controller uses contact conditioned Cartesian targets and LA-QDPP selection. SUMO uses its native G1 locomotion policy and box reward with CEM, optimizing base commands while the policy controls the limbs. Whole-body contact is permitted. The additional curve simulates the elite mean that SUMO executes. The scene is expressed in a rigid coordinate frame centered at the object goal. The runtime, reward, action representation and timing differ, so this comparison does not isolate the selector.</p><p>The five visible anchors summarize the reference path. In the optimized replay, the faint field shows recomputed contact scores and the outlined regions mark projected palm neighborhoods. In the SUMO replay, markers show body contact locations reconstructed from recorded states. SUMO moves the object 0.70 m in this 40 s trial and finishes 1.33 m from the target without falling. These individual development replays are not aggregate benchmark results.</p><p>At the planning level, maze candidates are checked in interaction order for reachability and collisions. When replanning is enabled, the resulting observation conditions a new plan after an object interaction. The long horizon experiment below illustrates this update.</p></details>''')
article.clear();article.append(BeautifulSoup(''.join(parts),'html.parser'));article['data-compact']='true'
(root/'index.html').write_text(str(soup).rstrip()+'\n')
