"""Present original-scene and CLEAR-scene execution with measured outcomes."""
from pathlib import Path
from bs4 import BeautifulSoup
root=Path(__file__).resolve().parents[1];soup=BeautifulSoup((root/'index.html').read_text(),'html.parser');article=soup.find(id='method-execution')
process=article.find(id='mpc-process');process_html=str(process) if process else ''
parts=['<h3>(d) Execution and replanning</h3><p class="method-lead">The controller tracks object targets and updates its commands from new observations.</p>']
groups=[('SUMO original box scene','A 1 m box with mass 10 kg starts 1 m from the goal. The baseline uses the upstream box scene and reset. Our controller is transferred to the same box geometry, mass, inertia, friction, and relative layout in its own runtime.',[
 ('mpc-stock-optimized','MPC w/ optimization (ours)','0.70 m moved · 0.34 m goal error · 60.1 s','The controller maintains bilateral palm contact but reaches its time limit.'),
 ('mpc-stock-baseline','MPC (SUMO)','0.70 m moved · 0.30 m goal error · 9.36 s','The original task reports success at its 0.30 m position tolerance and low object velocity.')]),
 ('CLEAR two gate scene','The same two gate development scene used by the controller comparison. The replay follows the first object interaction, with a 2 m reference path.',[
 ('mpc-optimized','MPC w/ optimization (ours)','1.97 m moved · 0.07 m goal error · 14.0 s','Contact conditioned targets guide the arms along the object reference.'),
 ('mpc-baseline','MPC (SUMO)','0.70 m moved · 1.33 m goal error · 40.0 s','Whole-body contact is permitted. Progress stalls without a fall.')])]
for title,intro,rows in groups:
 parts.append(f'<section class="mpc-scene-comparison"><h4>{title}</h4><p class="method-small-copy">{intro}</p><div class="experiment-matrix paired-matrix mpc-comparison">')
 for scene,label,metrics,detail in rows:
  inset='Body contact detail' if scene.endswith('baseline') else 'Ego RGB + paired palm regions'
  parts.append(f'''<article><h5>{label}</h5><div class="viewer experiment-viewer" data-scene="{scene}" data-title="{label}" data-ego="true"><video class="preview-video" muted playsinline controls data-autoplay preload="none" poster="assets/media/{scene}.png"><source src="assets/media/{scene}.mp4" type="video/mp4"></video><button class="launch" type="button">Play in 3D</button><figure class="ego-inset"><video muted playsinline preload="none" poster="assets/media/{scene}-ego.png"><source src="assets/media/{scene}-ego.mp4" type="video/mp4"></video><figcaption>{inset}</figcaption></figure></div><p class="mpc-outcome">{metrics}</p><p class="method-small-copy">{detail}</p></article>''')
 parts.append('</div></section>')
parts.append('''<p class="figure-caption">Videos preserve recorded durations. Smooth video frames interpolate measured poses. Play in 3D exposes the candidate trajectories, five reference anchors, and a synchronized contact view. Each result describes one seed and one scene, rather than aggregate benchmark performance.</p><details class="method-details"><summary>Controller settings and comparison scope</summary><p>The upstream G1 box task disables explicit left and right arm commands. Its MPC controls three base velocities, while the native G1 policy controls the limbs. This setting permits pushing with the body and explains why it does not independently reach with both arms. The original task succeeds within 0.30 m in each horizontal coordinate when object speed is below 0.10 m/s. Our controller uses a stricter 0.08 m goal tolerance and a 0.12 rad orientation tolerance.</p><p>Our controller uses contact conditioned Cartesian targets and LA-QDPP selection, with a 0.6 s horizon and a 0.1 s control interval. SUMO uses its native G1 policy, box reward, and Judo CEM, with a 2.5 s horizon and a 0.05 s control interval. Both evaluate 24 candidates. The original scene comparison retains each runtime’s robot initialization and contact solver. The CLEAR scene is expressed in a rigid goal centered frame for SUMO. These comparisons include differences in runtime, reward, action representation, stopping conditions, and timing. They do not isolate the selector.</p><p>The optimized 3D replay includes recomputed contact scores and outlined palm neighborhoods. The SUMO detail view shows body contacts and hides walls for visibility. All robot and object motion comes from physical execution records. The CLEAR scene is a development example and is not reported as held out benchmark performance.</p></details>''')
parts.append(process_html)
article.clear();article.append(BeautifulSoup(''.join(parts),'html.parser'));article['data-compact']='true'
(root/'index.html').write_text(str(soup).rstrip()+'\n')
