"""Present the paired physical execution with synchronized ego contact insets."""
from pathlib import Path
from bs4 import BeautifulSoup
root=Path(__file__).resolve().parents[1];soup=BeautifulSoup((root/'index.html').read_text(),'html.parser');article=soup.find(id='method-execution')
parts=['<h3>(d) Execution and replanning</h3><p class="method-lead">The controller tracks object targets and updates its commands from new observations.</p><div class="experiment-matrix paired-matrix mpc-comparison">']
for scene,title,detail in [('mpc-optimized','Palm tracking MPC (ours)','Cartesian palm targets guide the arms through the push.'),('mpc-baseline','Naive MPC','Direct joint commands are optimized by CEM.')]:
 parts.append(f'''<article><h4>{title}</h4><div class="viewer experiment-viewer" data-scene="{scene}" data-title="{title}" data-ego="true"><img class="preview-image" src="assets/media/{scene}.png" alt="Robot, object targets, and recorded candidate palm paths" width="700" height="540" loading="lazy"><button class="launch" type="button">Play in 3D</button><figure class="ego-inset"><video muted playsinline preload="none" poster="assets/media/{scene}-ego.png"><source src="assets/media/{scene}-ego.mp4" type="video/mp4"></video><figcaption>Ego RGB + paired palm regions</figcaption></figure></div><p class="method-small-copy">{detail}</p></article>''')
parts.append('''</div><p class="figure-caption">Five elevated anchors summarize each object reference path. Green marks ours and red marks the baseline. Thin curves show sampled palm trajectories, while the thick curve shows the executed candidate. The ego view follows the same playback time as its 3D scene.</p><p class="method-small-copy">The faint surface field shows learned contact scores. Two outlined regions locate the recorded left and right palms projected onto the object. These geometric contact neighborhoods are separate from the learned affordance field and do not assert measured contact forces.</p><details class="method-details"><summary>Replay and controller details</summary><p>Both panels show the first object interaction from the same development scene and planning seed. Each controller evaluates 24 candidates over a 0.6 s horizon and applies a 0.1 s segment. Their recorded durations differ and are preserved.</p><p>Ours uses Cartesian palm tracking with a gain of 0.25 and LA-QDPP candidate selection. The baseline uses a direct joint CEM port with top-k selection and executes the elite mean. Its additional curve is a physics rollout of that mean. This port does not use the original upstream runtime. The controllers differ in both action representation and selection, so this comparison does not isolate the selector.</p><p>The five visible anchors are spaced along the original eight target poses for clarity. Contact scores are recomputed visualizations, normalized by each frame’s maximum score. They are not archived controller telemetry. These individual development replays are not aggregate benchmark results.</p><p>At the planning level, maze candidates are checked in interaction order for reachability and collisions. When replanning is enabled, the resulting observation conditions a new plan after an object interaction. The long horizon experiment below illustrates this update.</p></details>''')
article.clear();article.append(BeautifulSoup(''.join(parts),'html.parser'));article['data-compact']='true'
(root/'index.html').write_text(str(soup).rstrip()+'\n')
